export const STORAGE = {
    SAVE: {
        REQUEST: 'REQUEST_SAVE_STORAGE',
        SUCCESS: 'SUCCESS_SAVE_STORAGE',
        FAILURE: 'FAILURE_SAVE_STORAGE'
    },
    REMOVE: {
        REQUEST: 'REQUEST_REMOVE_STORAGE',
        SUCCESS: 'SUCCESS_REMOVE_STORAGE',
        FAILURE: 'FAILURE_REMOVE_STORAGE'
    },
    GET: {
        REQUEST: 'REQUEST_GET_STORAGE',
        SUCCESS: 'SUCCESS_GET_STORAGE',
        FAILURE: 'FAILURE_GET_STORAGE'
    },
    SET: 'SET_ITEM',
    CLEAN: 'CLEAN_ITEM',
}