export const VIN = {
    LOAD: {
        LAST_THREE_VIN: 'LOAD_LAST_THREE_VIN'
    },
    CLEAN: {
        STORAGE_TYPE: 'CLEAN_BY_STORAGE_TYPE',
    },
    GET_DECODE: {
        SUCCESS: 'GET_DECODE_VIN_SUCCESS',
        FAILURE: 'GET_DECODE_VIN_FAILURE',
    },
    GET_VEHICLE_VARIABLES: {
        SUCCESS: 'GET_VEHICLE_VARIABLES_SUCCESS',
        FAILURE: 'GET_VEHICLE_VARIABLES_FAILURE'
    },
    GET_VARIABLE_DETAILS: {
        SUCCESS: 'GET_VARIABLE_DETAILS_SUCCESS',
        FAILURE: 'GET_VARIABLE_DETAILS_FAILURE'
    },
}