export const VIN = {
    GET_DECODE: {
        SUCCESS: 'GET_DECODE_VIN_SUCCESS',
        FAILURE: 'GET_DECODE_VIN_FAILURE',
    },
    GET_VEHICLE_VARIABLES: {
        SUCCESS: 'GET_GET_VEHICLE_VARIABLES_SUCCESS',
        FAILURE: 'GET_GET_VEHICLE_VARIABLES_FAILURE'
    }
}